### ISSUE TITLE
Functions should check if child declares

### ISSUE THREAD

**Issue by timiwahalahti** [samikeijonen/sanse#1]
Example functions in `inc/template-tags.php` should be wrapper inside `if( !function_exists(` ... to allow functionality override in child themes.

**Comment by samikeijonen** [comment]
I have removed all the pluggable functions on purpose. I don't think that's the best way to modify things in child theme (or in a plugin).
- Maintaining pluggable function in child theme is hard. You might break things eventually.
- Core moved away from pluggable functions long time ago. At least I think so:)

There probably isn't perfect way but better way is
- overwriting template files with custom functions if needed.
- with filters and hooks.
