### ISSUE TITLE
Make links work on blog frontpage?

### ISSUE THREAD

**Issue by poVoq** [samikeijonen/sanse#4]
Very nice theme, but only the title and the "read more" link work on the blog frontpage, thus if readers want to follow a link in a short post they have to open the full blog page and can not just click on the frontpage.

Any idea if there is a quick fix for that? Thanks!

**Comment by samikeijonen** [comment]
Yep, that's how WP Core the_excerpt function works. It strips all the markup like links and images. You can write custom excerpt if you want to have links in there.
