### ISSUE TITLE
Posted no date not shown for non-standard blog-posts

### ISSUE THREAD

**Issue by poVoq** [samikeijonen/sanse#5]
If I use this theme with the PodLove plugin, the new Podcast entries show up nicely on the front page alongside the blog entries, but the "Posted on ..." text is missing for the Podcasts.

Any idea if this can be fixed easily? Thanks!

**Comment by samikeijonen** [comment]
I assume Podcast entries is Custom Post Type (CPT). You could create template file for that CPT to child theme and use `sanse_posted_on()` in there.

**Comment by poVoq** [comment]
Thanks!
